const COPY = {
  createPost: {
    hashtagPoolSelector: {
      copy: 'Copy',
      delete: 'Delete',
      toasts: {
        success: {
          copy: 'Hashtags copied to clipboard',
        },
        error: {
          delete: 'Failed to delete hashtag pool. Please try again.',
          copy: 'Failed to copy hashtags to clipboard.',
        },
      },
    },
  },
  socialCalendar: {
    socialCalendar: 'Social Calendar',
    socialCalendarDescription: 'Plan and preview upcoming social media posts',
    layoutDescription:
      'Drag to reorder · Click empty to create · Click post to edit · Double-click to preview',
    addPost: 'Add Post',
    clickToCreate: 'Click to create',
    hoverPostHelperText: 'Click to edit · Double-click to preview · Drag to reorder',
    hoverPublishedPostHelperText: 'Click to edit · Double-click to preview',
    compose: 'Compose',
    layout: 'Layout',
    calendar: 'Calendar',
    platforms: 'Platforms',
    grid: 'Grid',
    quickPost: 'Quick Post',
    templates: 'Templates',
    bulkSchedule: 'Bulk Schedule',
    tagFilter: 'Tags',
    tagFilterPlaceholder: 'Filter by tags',
    noPostsMatchingFilters: 'No posts match the active filters',
    noPostsMatchingFiltersHint: 'Try removing some filters to see posts',
    clearFilters: 'Clear filters',
    allPlatforms: 'All Platforms',
    platformLabel: 'Platform',
    sortByPlaceholder: 'Sort by…',
    sortNewest: 'Newest first',
    sortOldest: 'Oldest first',
    sortByStatus: 'By status',
    sortByPlatform: 'By platform',
    sortDefaultOrder: 'Default order',
    noPostsScheduled: 'No posts scheduled',
    noPostsScheduledHint: 'Add your first post to the calendar',
    signOffCalendar: 'Sign Off Calendar',
    signOffApprovedBy: 'Sign Off Approved By',
    signOffDate: 'Sign Off Date',
    approveAllPosts: 'Approve All Posts',
    approverNamePlaceholder: 'Enter approver name...',
    approverNameRequired: 'Please enter approver name',
    cancel: 'Cancel',
    discardChangesTitle: 'Discard changes?',
    discardNewPostDescription:
      'You have unsaved changes. Are you sure you want to start a new post?',
    discardNewPostConfirm: 'Discard & Start New',
    discardViewSwitchDescription:
      'You have unsaved changes in the composer. Are you sure you want to switch views without saving?',
    discardViewSwitchConfirm: 'Discard Changes',
    keepEditing: 'Keep Editing',
    draggedToPastTime:
      "This post's scheduled time is now in the past. Open the post to update the time.",
    swapDatesOnDrag: 'Swap dates of posts when dragging',
    untitled: 'Untitled',
    unscheduled: 'unscheduled',
    toasts: {
      success: {
        swappedDates: (nameA: string, dateB: string, nameB: string, dateA: string) =>
          `Swapped dates: "${nameA}" → ${dateB}, "${nameB}" → ${dateA}`,
      },
      error: {
        reorderPosts: 'Failed to update post order. Please try again.',
        publishedPost: 'Published posts cannot be reordered.',
      },
    },
  },
  postStatusLegend: {
    groupLabel: 'Filter by post status',
    clearFilters: 'Clear filters',
    chipAriaLabel: (label: string, description: string, count: number) =>
      `Filter by ${label}: ${description}. ${count} post${count === 1 ? '' : 's'}.`,
  },
  platformFilter: {
    groupLabel: 'Filter by platform',
    chipAriaLabel: (platformLabel: string) => `Filter by ${platformLabel}`,
  },
  tagsFilter: {
    triggerLabel: 'Tags',
    triggerAriaLabel: (count: number) =>
      count === 0
        ? 'Filter by tags'
        : `Filter by tags. ${count} tag${count === 1 ? '' : 's'} selected.`,
    noResults: 'No tags found',
  },
  deletedPosts: {
    tabDescription:
      'Deleted posts are kept here for 30 days so you can restore a draft copy. After 30 days they are eligible for permanent deletion.',
    emptyState: 'No deleted posts',
    restore: 'Restore',
    deleteForever: 'Delete Forever',
    countdown: {
      daysLeft: (days: number) => (days === 1 ? '1 day left' : `${days} days left`),
      purgePending: 'Purge pending',
      ariaLabel: (days: number) =>
        days === 1 ? '1 day until permanent deletion' : `${days} days until permanent deletion`,
    },
    dialogs: {
      deletePublished: {
        title: 'Delete this post?',
        bodyLead:
          'The post will be moved to the Deleted tab. After 30 days it will be eligible for permanent deletion.',
        bodyUnpublish: (platforms: string) =>
          `This does NOT remove the post from ${platforms}. To take it down from those platforms, remove it there directly.`,
        bodyRestore:
          "You can restore a draft copy from the Deleted tab within 30 days. Restored posts return as drafts in this app only — they won't retain any original engagement.",
        cancel: 'Cancel',
        confirm: 'Delete',
      },
      deleteDraft: {
        title: 'Delete this draft?',
        body: "This draft will be moved to the Deleted tab. You'll have 30 days to restore it before it's permanently deleted.",
        cancel: 'Cancel',
        confirm: 'Delete',
      },
      permanentDelete: {
        title: 'Permanently delete this post?',
        body: "This can't be undone. The post and its history will be removed immediately.",
        cancel: 'Cancel',
        confirm: 'Delete Forever',
      },
    },
    toasts: {
      softDeleted: 'Post moved to Deleted tab',
      restored: 'Post restored to drafts',
      permanentlyDeleted: 'Post permanently deleted',
      softDeleteFailed: "Couldn't delete the post. Please try again.",
      restoreFailed: "Couldn't restore the post. Please try again.",
      permanentDeleteFailed: "Couldn't permanently delete the post. Please try again.",
    },
  },
  calendarPostModal: {
    editPost: 'Edit Post',
    createPost: 'Create Post',
    tags: 'Tags',
    aiAssistant: 'AI Assistant',
    preview: 'Preview',
    compose: 'Compose',
    approvalWorkflow: 'Approval Workflow',
    comments: 'Comments',
    activity: 'Activity',
    teamFeedback: 'Team Feedback',
    captionPlaceholder: 'Start writing your post here...',
    seePreviewHere: "See your post's preview here",
    yourAccount: 'Your Account',
    justNow: 'Just now',
    captionPreviewPlaceholder: 'Your caption will appear here…',
    dragAndDrop: 'Drag & drop or',
    selectAFile: 'select a file',
    recurringPost: 'Recurring Post',
    recurringEnabled: 'Configure a recurring schedule for this post below.',
    recurringDisabled: 'This post will be scheduled once.',
    repeat: 'repeat',
    daily: 'Daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
    endDateOptional: 'End date (optional)',
    schedule: 'Schedule',
    bestTimes: 'Best Times',
    bestTimesForPlatform: 'Best times for {platform} based on typical audience activity:',
    apply: 'Apply →',
    date: 'Date',
    time: 'Time',
    timezone: 'Timezone',
    timezoneSearchPlaceholder: 'Search timezone…',
    timezoneNoResults: 'No timezone found.',
    requiresApproval: 'Requires Approval',
    approvalEnabled: 'This post will be sent for team approval before going live.',
    approvalDisabled: 'This post will be scheduled without requiring approval.',
    approvalPermissionTooltip:
      'You do not have permission to change this setting. Please contact an admin for assistance.',
    deletePost: 'Delete Post',
    saveDraft: 'Save Draft',
    draftSaved: 'Saved',
    revertToDraft: 'Revert to Draft',
    revertToDraftTitle: 'Revert to Draft?',
    revertToDraftDescription:
      'This will revert the post to draft status, remove the assigned reviewer, reset priority, and clear the due date and note. The post will need to go through the approval workflow again.',
    revertToDraftConfirm: 'Revert to Draft',
    newPost: 'New Post',
    submitForApproval: 'Submit for Approval',
    sendForApproval: 'Send for Approval',
    approvalReviewerRequired: 'Please assign at least one reviewer.',
    approvalPriorityRequired: 'Please select a priority.',
    approvalDueDateRequired: 'Please set a due date.',
    composeCaptionRequired: 'Please add a caption.',
    composePlatformsRequired: 'Please pick at least one platform.',
    approvalDueDatePast: 'Due date cannot be in the past.',
    approvalDueDateAfterSchedule:
      "Review due date must leave at least one hour before the post's scheduled time.",
    approvalDueDateHint:
      "Reviewer has until the earlier of end of this day or one hour before the post's scheduled time.",
    updatePost: 'Update Post',
    schedulePost: 'Schedule Post',
    deleteConfirmTitle: 'Delete Post',
    deleteConfirmDescription:
      'Are you sure you want to delete this post? It will be removed from the following platform(s): {platforms}',
    delete: 'Delete',
    cancel: 'Cancel',
    connectDropboxTitle: 'Connect Dropbox First',
    connectDriveTitle: 'Connect Google Drive First',
    connectDropboxDescription:
      "Dropbox isn't connected in this workspace yet. Open Settings to review the current integrations setup before using Dropbox media here.",
    connectDriveDescription:
      "Google Drive isn't connected in this workspace yet. Open Settings to review the current integrations setup before using Drive media here.",
    openSettings: 'Open Settings',
    notNow: 'Not Now',
    twitterDisplayName: 'Twitter / X',
    whereToPost: 'Where would you like to share this post?',
    whereHasPosted: 'Posted to these platforms:',
    exceededCharLimit: 'Exceeded limit of {limit} characters for {platform}',
    cropTitle: 'Crop Image',
    cropForPlatform: 'Crop for {platform}',
    saveCrop: 'Save Crop',
    resetCrop: 'Reset',
    cropInstructions: 'Drag to reposition or resize. Recommended ratio for {platform} is {ratio}.',
    cropRecommended: '{ratio} recommended',
    cropCustom: 'Custom',
    cropPresets: 'Presets',
    cropShiftHintPrefix: 'Hold',
    cropShiftHintSuffix: 'while resizing to lock the aspect ratio.',
    cropRotateLeft: 'Rotate left',
    cropRotateRight: 'Rotate right',
    cropFlipHorizontal: 'Flip horizontal',
    cropFlipVertical: 'Flip vertical',
    cropSafeZones: 'Safe zones',
    cropSafeZonesTooltip:
      "Safe zones mark the area that stays visible across all placements of this format — e.g. the part of an Instagram Reel that isn't hidden behind UI overlays. Keep key content inside the dashed lines.",
    cropSaved: 'Crop saved — preview updated.',
    cropApplied: 'Crop applied for {platform}',
    cropReset: 'Crop reset for {platform}',
    shiftKey: 'Shift',
    uploadImagesFailed: 'Failed to upload images.',
    uploadVideoFailed: 'Failed to upload video.',
    videoBeforeImages: 'Remove the selected video before adding images.',
    imagesBeforeVideo: 'Remove the selected images before adding a video.',
    mixedMediaDrop: 'Choose either images or one video, not both at the same time.',
    oneVideoOnly: 'Only one video can be attached to a post.',
    scheduledTimeInFuture: 'Scheduled time must be in the future.',
    continueToApproval: 'Continue to Approval',
    saveFailed: 'Failed to save post. Please try again.',
    submitForApprovalFailed: 'Failed to submit post for approval. Please try again.',
    approvalUpdateFailed: 'Failed to update approval. Please try again.',
    tagSaveFailed: 'Failed to save tags. Please try again.',
    platformUpdateFailed: 'Failed to update platforms. Please try again.',
    saveSuccessDraft: 'Draft saved.',
    saveSuccessScheduled: 'Post scheduled.',
    resubmitForApproval: 'Resubmit for Approval',
    saveSuccessPendingApproval: 'Post sent for approval.',
    saveSuccessPublished: 'Post published.',
    saveSuccessDefault: 'Post saved.',
    viewPost: 'View Post',
  },
  linkInserter: {
    title: 'Insert Link',
    urlLabel: 'URL',
    urlPlaceholder: 'https://example.com',
    displayTextLabel: 'Display text',
    displayTextPlaceholder: 'Display text (optional)',
    insert: 'Insert',
    urlError: 'Please enter a valid URL starting with http:// or https://',
  },
  bufferComposer: {
    tags: 'Tags',
    addPhoto: 'Add Photo',
    addFromLibrary: 'Add from Library',
    library: 'Library',
    removeVideoFirst: 'Remove the selected video before adding images.',
    removeImagesFirst: 'Remove the selected images before adding a video.',
    failedUploadVideo: 'Failed to upload video.',
  },
  mediaUpload: {
    imagesSelected: (count: number, max: number) =>
      `${count}/${max} ${count === 1 ? 'image' : 'images'} selected. Video upload is disabled while images are attached.`,
    videoSelected: '1 video selected. Image upload is disabled while a video is attached.',
    mediaHint: (maxImages: number, imageFormats: string, videoFormats: string) =>
      `Add up to ${maxImages} images (${imageFormats}) or one video (${videoFormats}).`,
  },
  tagSelector: {
    placeholder: 'Add tags…',
    searchPlaceholder: 'Search tags…',
    noResults: 'No tags found.',
    loading: 'Loading…',
    createTag: (name: string) => `Create tag "${name}"`,
    createError: 'Failed to create tag. Please try again.',
    deleteSuccess: (name: string) => `Tag "${name}" deleted.`,
    deleteError: 'Failed to delete tag. Please try again.',
    atLimit: 'Posts can only have 10 tags.',
    deleteTagLabel: (name: string) => `Delete tag ${name}`,
    colorLabel: 'Color',
    createWithColor: 'Create',
  },
  tagPill: {
    // Tag-specific label so screen readers can distinguish between multiple pills.
    removeLabel: (name: string) => `Remove tag ${name}`,
  },
  socialTags: {
    activeTab: 'Active',
    archivedTab: 'Archived',
    archiveSuccess: (name: string) => `"${name}" archived`,
    unarchiveSuccess: (name: string) => `"${name}" unarchived`,
    archiveError: 'Failed to update tag. Please try again.',
    duplicateNameError: 'A tag with this name already exists.',
    noActiveTags: 'No active tags.',
    noArchivedTags: 'No archived tags.',
    postCount: (n: number) => `${n} post${n === 1 ? '' : 's'}`,
    archiveLabel: 'Archive',
    unarchiveLabel: 'Unarchive',
  },
  platformBadges: {
    overflow: (count: number) => `+${count}`,
  },
  hashtagManager: {
    searchPlaceholder: 'Search hashtags...',
    addToFavorites: 'Add to Favorites',
    noPoolsFound: 'No hashtag pools found',
    createFirstPool: 'Create your first pool above',
    delete: 'Delete',
    cancel: 'Cancel',
    deletePoolTitle: 'Delete Hashtag Pool',
    deletePoolConfirm:
      'Are you sure you want to delete this hashtag pool? This action cannot be undone.',
    categoriesTitle: 'Categories',
    allHashtags: 'All Hashtags',
    favorites: 'Favorites',
    uncategorized: 'Uncategorized',
    createPoolTitle: 'Create New Hashtag Pool',
    newCategory: 'New Category',
    hashtagsPlaceholder: 'e.g. #marketing #brand #social (# will be added automatically)',
    addPool: 'Add',
    poolNamePlaceholder: 'Pool name...',
    newCategoryPlaceholder: 'New category name...',
    newCategoryAdd: 'Add',
    newCategoryCancel: 'Cancel',
    createPoolError: 'Failed to create hashtag pool. Please try again.',
  },
  postApprovalPanel: {
    heading: 'Approval Workflow',
    stages: {
      draft: { label: 'Draft', description: 'Post is being created' },
      pendingApproval: { label: 'Awaiting Approval', description: 'Post is under review' },
      approved: { label: 'Approved', description: 'Ready to publish' },
      published: { label: 'Published', description: 'Live on platforms' },
    },
    stageActors: {
      submitted: 'Submitted',
      approved: 'Approved \u2713',
      rejected: 'Rejected',
      changesRequested: 'Changes Requested',
      assignedReviewer: 'Assigned reviewer',
    },
    changesNeeded: 'Changes Needed',
    changesRequestedHint: 'Changes have been requested \u2014 update and resubmit.',
    noActivityYet: 'No activity yet',
    postRejected: 'Post Rejected',
    resubmit: 'Resubmit',
    reviewerLabel: 'Reviewers',
    assignReviewerPlaceholder: 'Assign reviewer\u2026',
    priorityLabel: 'Priority',
    priorityLow: 'Low',
    priorityNormal: 'Normal',
    priorityHigh: 'High',
    priorityUrgent: 'Urgent',
    dueDateLabel: 'Due Date',
    noteLabel: 'Note',
    notePlaceholder: 'Add a note to your reviewers (optional)',
    actionsLabel: 'Actions',
    submitForApproval: 'Submit for Approval',
    resubmitForApproval: 'Resubmit for Approval',
    approve: 'Approve',
    reject: 'Reject',
    requestChanges: 'Request Changes',
    approvedBy: (name: string) => `Approved by ${name}`,
    saving: 'Saving\u2026',
    history: (count: number) => `History (${count})`,
  },
  approvalQueueView: {
    reviewer: 'Reviewers',
    notAssigned: 'Not assigned',
    priority: 'Priority',
    notSet: 'Not set',
    dueDate: 'Due Date',
    note: 'Note',
    noNote: 'No note',
  },
  approvalWidget: {
    version: 'Version',
    views: 'Views',
    approved: 'Approved',
    rejectedOrChangesRequested: 'Rejected / Changes Requested',
    noDueDateSet: 'No Due Date Set',
    overdue: 'OVERDUE',
    leftUntilDueDate: 'left until Due Date',
    dueDatePrefix: 'Due Date:',
    postDatePrefix: 'Post Date:',
    noPostDateSet: 'No Post Date Set',
  },
  postVersion: {
    versionLabel: (n: number) => `Version: ${n}`,
    versionShort: (n: number) => `v${n}`,
  },
  postApprovalView: {
    postNotFound: 'Post not found.',
    backToAllChannels: 'Back to All Channels',
    backToSocialCalendar: 'Back to Social Calendar',
    mediaRetainedNotice:
      'Media retained for version history — not transferred to the Approved Media Database.',
    workflow: 'Workflow',
    editPost: 'Edit Post',
  },
  postCommentThread: {
    emptyTitle: 'No comments yet',
    emptySubtitle: 'Leave feedback or notes for the team.',
    inputPlaceholder: 'Add a comment\u2026 use @ to mention someone',
  },
  approvalActionDrawer: {
    rejectedLabel: 'Reason for Rejection',
    approvedLabel: 'Approval Note',
    changesRequestedLabel: 'Changes Requested',
    rejectedSubmit: 'Reject',
    approvedSubmit: 'Approve',
    changesRequestedSubmit: 'Request Changes',
    placeholder: {
      rejected: 'Explain why this post is being rejected\u2026',
      approved: 'Add an approval note (optional)\u2026',
      changes_requested: 'Describe the changes needed\u2026',
    },
    badge: {
      rejection: 'Rejection',
      approval: 'Approval',
      request_changes: 'Changes Requested',
    },
  },
  general: {
    close: 'Close',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    update: 'Update',
    confirm: 'Confirm',
    yes: 'Yes',
    no: 'No',
  },
  mediaLibraryModal: {
    title: 'Select Media Library Images',
    cancel: 'Cancel',
    searchPlaceholder: 'Search media library images',
    loading: 'Loading media library...',
    empty: 'No image assets found in the Media Library.',
  },
  authError: {
    heading: 'Something went wrong',
    defaultMessage: 'The app failed to load. Please refresh to try again.',
  },
  namePrompt: {
    saveFailed: 'Failed to save name. Please try again.',
  },
  reviewerPicker: {
    placeholder: 'Assign reviewers\u2026',
    searchPlaceholder: 'Search by name or email\u2026',
    noResults: 'No matching team members.',
    removeLabel: (name: string) => `Remove ${name}`,
  },
  approvalProgress: {
    allApproved: (count: number) => `All ${count} reviewers approved`,
    approvedBy: (name: string) => `Approved by ${name}`,
    approvedGeneric: 'Approved',
    partialApproval: (approved: number, total: number) => `${approved}/${total} reviewers approved`,
    pendingReview: (count: number) => `${count} reviewer${count === 1 ? '' : 's'} pending`,
  },
  reviewerStatus: {
    pending: 'Pending',
    approved: 'Approved',
    rejected: 'Rejected',
    changes_requested: 'Changes Requested',
  },
  approvalEmail: {
    untitledPost: 'Untitled post',
    fallbackSubmitter: 'A teammate',
    missingValue: '—',
  },
  projects: {
    myProjects: 'My Projects',
    readOnlyBadge: 'Read-only',
    editProject: 'Edit Project',
    deleteProject: 'Delete Project',
    deleteDialog: {
      title: 'Delete this project?',
      description:
        'This cannot be undone. Tasks, milestones, and time logs will not be deleted, but they will no longer appear under any project.',
      cancel: 'Cancel',
      confirm: 'Delete Project',
      confirmPending: 'Deleting…',
    },
    toasts: {
      updateError: 'Failed to update project',
    },
    userPicker: {
      placeholder: 'Add team members…',
      searchPlaceholder: 'Search by name or email…',
      selectedCount: (count: number) => `${count} selected`,
      emptyTitle: 'No teammates in your department.',
      emptyHint: 'Ask an admin to assign cross-department teammates.',
      noResults: 'No matching teammates.',
      removeLabel: (label: string) => `Remove ${label}`,
    },
  },
};

export default COPY;
